### ISSUE TITLE
NameError while creating MondayClient

### ISSUE THREAD

**Issue by booey811** [trix-solutions/moncli#14]
Hi Team,

Great work on this package, it holds so much potential!

Unfortunately, I'm getting a NameError whenever I try to create the MondayClient object. Im using MacOS High Sierra 10.13.6 with Python 3.8.

Sorry if it seems like a rookie error but I'm new to this, I hope you can help!

Thakns in advance!

**Comment by lalym** [comment]
the same bug
NameError: name 'MondayClient' is not defined

**Comment by Ashatz** [comment]
@booey811, thank you very much for getting back to me.  From the looks of it, it seems that you are not importing the MondayClient object into the python script.  

`from moncli import MondayClient`
or 
`moncli.MondayClient`

If this is not your issue, would you and @lalym be able to provide some code samples?  Thank you very much!

**Comment by Ashatz** [comment]
Ah, I see the source of confusion. There is an error in the documentation. I will update this right away.

**Comment by Ashatz** [comment]
@booey811 and @lalym, I have fixed the documentation such that importing the MondayClient object is more clear.  Please let me know if you run into any more issues with this.
