### ISSUE TITLE
Apostraphe in a name seems to cause issues for API

### ISSUE THREAD

**Issue by ManjotS** [trix-solutions/moncli#208]
This throws an error from the API:
item.change_multiple_column_values({'name': "O'Dool", 'text': 'sometext'})

This does not:
item.change_multiple_column_values({'name': 'ODool', 'text': 'sometext'})

**Comment by Ashatz** [comment]
Hello @ManjotS,

Thank you for your feedback.  I have identified the issue and have fixed it with the latest patch version release (v2.0.6) available for download.  

Your feedback is appreciated! Please let me know if this does not resolve your issue.

Thanks!
