### ISSUE TITLE
Iterating Columns Fails

### ISSUE THREAD

**Issue by matpearsons** [trix-solutions/moncli#210]
This appears to have only just started happening and only against the European Instances, but when I run an established script (that worked last week) that contains:

        src_items = src_board.get_items()
        for src_item in src_items:
            for src_column in src_item.column_values:

I get the error:

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d'

Again running the same script against the US instance completes correctly. 

Appears to happen when you hit a column of type Date that is not populated (not has ever been) populated with any date on a board that has been imported from an .xlsx. Even if you are testing against the title and not touching the value.

**Comment by Ashatz** [comment]
Hello Matt,

Thank you for your patience regarding this issue.  I have identified it and resolved it with PR #211

The new patch version (2.0.7) contains the new fixes.  Please let me know if you still experience problems regarding this issue.

Thank you and happy coding!

**Comment by matpearsons** [comment]
Andrew,

Many thanks for providing the patch, and sorry its taken so long to get back to you, ive been out the office. 
Unfortunately im still experiencing the same issue even after installing  2.0.8. Giving it some more thought it appears to only occur if the column is created programmatically using Moncli, if the columns is created manually through the Monday.com UI then I believe it works ok. Hence me thinking it had previously worked (ie. it was before I had coded the column creation and was manually adding columns). 

Ive attached  the traceback if that is of any use. 

Cheers

Mat

[traceback.txt](https://github.com/trix-solutions/moncli/files/7972140/traceback.txt)

**Comment by Ashatz** [comment]
Hello Mat

Thank you for your patience. It has been a busy week this past week.

Currently, I am unable to reproduce your issue. Would it at all be possible for you to run a query in the monday.com API playground to retrieve the data for an item that is causing this issue? I would like to better understand the state of your data, for there appear to be differences (not surprising considering monday.com).

Thanks again, and I look forward to hearing from you regarding this.

Pleasure and an honor,

Andrew

------- Original Message -------
