### ISSUE TITLE
Breaking Change introduced at 2.0.6 for get_items_by_multiple_column_values

### ISSUE THREAD

**Issue by Mariadb-colebusby** [trix-solutions/moncli#220]
I've been leveraging the moncli library for several months and in trying to bring my frameworks up to date, I have found that the change introduced in 2.0.6 to allow for apostrophe's in values has broken the ability to provide a list to the function.

https://github.com/trix-solutions/moncli/commit/9a46f10800a46d310a05f1b97c4e2180b779d95e is the commit in question.

Method Signature in use:
```
get_items_by_multiple_column_values(
            myBoard.columns['text'],
            [data['company']],
            get_column_values=True,
            as_model=None
        )
```

The resulting change creates an invalid graphQL query on lists.

column_values:['data['company']'s value is here']

Monday's API throws parse error on ' after [

**Comment by Ashatz** [comment]
Hello @Mariadb-colebusby,

I have identified the issue have addressed with PR #222.  Please let me know if you continue running into issues.

Thank you and happy coding!
