### ISSUE TITLE
add_item timeout for HTTP connection pool (read timeout = 10)

### ISSUE THREAD

**Issue by mparthasarathy25** [trix-solutions/moncli#224]
I was working with the board.add_item function and noticed that when running the function for multiple items in a dataframe, I received an error with a readtimeout. Is there any way to increase the amount of time it takes for the function to timeout? The default seems to be 10, but I would like for it to be increased.

<img width="845" alt="Screen Shot 2022-07-07 at 11 45 26 AM" src="https://user-images.githubusercontent.com/87879274/177827013-b28149fa-70bd-4620-8b30-a5b9dae565e8.png">

**Comment by aswathm78** [comment]
You can set a timeout in the beginning of your script like this
`moncli.api.connection_timeout = 30`

**Comment by mparthasarathy25** [comment]
@aswathm78 
I must've missed that part of the documentation! Thank you for the help!
