### ISSUE TITLE
Cannot import name 'MondayClient' from 'moncl

### ISSUE THREAD

**Issue by takinmade** [trix-solutions/moncli#225]
Error
====  
File "...Monday_API\API_upload_file_DEV.py", line 6, in <module>
    from moncli import MondayClient
ImportError: cannot import name 'MondayClient' from 'moncli' (C:\Python310\lib\site-packages\moncli\__init__.py)

Versions
====
Python. 3.10.5
moncli. 2.0.14

**Comment by aswathm78** [comment]
Try this 
`from moncli.entities import MondayClient`

instead of 
`from moncli import MondayClient`

**Comment by aswathm78** [comment]
@takinmade 
Happy to help. Please close this issue if its resolved.

Thanks
