### ISSUE TITLE
Item.change_name Documentation Typo

### ISSUE THREAD

**Issue by booey811** [trix-solutions/moncli#226]
Hi Team,

In the docs, the Item entity is described as having a "change_name" method, however today I saw that the method is in fact;

Item.change_item_name()

Hope this helps and I haven't misread anything!

**Comment by Ashatz** [comment]
Hello @booey811,

Thank you for bringing this to our attention.  

I apologize for getting back so late, as this message found its way to my spam folder...

The documentation has been changed to reflect _item.change_item_name()_ as you stated above.

All the best!

Andrew
