### ISSUE TITLE
Timeline Fields causing get_items crash

### ISSUE THREAD

**Issue by Mariadb-colebusby** [trix-solutions/moncli#227]
https://github.com/trix-solutions/moncli/blob/6bb05061c41b70f1cb71c9c0cfc6bd76483dbcde/moncli/column_value/complex.py#L147

When a timeline field _somehow_ gets an errant value without from, or to values (example below), the library fails to pull in items from get_items calls.

The following is an example from our board. In our efforts with monday.com support to attempt to get more information on how this can occur, they were unable to successfully replicate this issue in their API. FURTHER, these fields bypass the audit log/activity log and the support teams failed to update their API to track these changes.
```
{
  "id": "timeline",
  "value": "{\"changed_at\":\"2022-07-11T13:08:20.385Z\"}",
  "text": ""
}
```

**Comment by Mariadb-colebusby** [comment]
I believe modifying the try/except in the given file or adding an additional to return a null field value would be the best solution to move forward.

**Comment by Mariadb-colebusby** [comment]
@ManjotS 's PR would be satisfactory to our needs
<img width="555" alt="Screen Shot 2022-07-29 at 11 33 09 AM" src="https://user-images.githubusercontent.com/89663695/181823104-cf8748c3-cfec-48ea-9d66-22a4e06c6a56.png">
.

**Comment by Ashatz** [comment]
@Mariadb-colebusby I would concur with you on both regards.  The monday.com api is truly a strange beast...  The fix that was submitted is indeed satisfactory.  

Thank you both for bringing this to my attention.  I will get this merged.
