### ISSUE TITLE
Unable to Get Items By Column Value

### ISSUE THREAD

**Issue by booey811** [trix-solutions/moncli#25]
Hi!!

Apologies for bothering you again, but when I try to create a status column value (with a view to using this column value to search for items containing that column value), I receive:

  File /moncli/columnvalue.py", line 682, in create_column_value
    return StatusValue(id, title, label=kwargs['label'], settings=kwargs['settings'])
KeyError: 'settings'

The code that calls the create column value function is: 

    sync_val = create_column_value(id='status5', title='Sync', column_type=ColumnType.status, label='Sync Now')

Would you have any insight into what I'm doing wrong?

Thanks in advance :)

**Comment by Ashatz** [comment]
Hello @booey811, I am sorry to get back to you so late... 

I will take a look into this.  Please note that I would to make another minor release within the next week, and I will confirm that this issue is addressed.  

All the best!

**Comment by Ashatz** [comment]
Hello @booey811.

I am sorry to get back to you late at this time. Other projects have occupied my time as of late. 

To answer your question, the 'settings' key-word argument (kwargs) is the StatusSettings object created from the column's settings_str attribute.  You can get this object by querying for the status column in question and passing in the settings attribute as a kwarg (settings=column.settings).

I would refrain from using this method if you have to, for the upgrades with the next minor release will address much of these underlying processes.  

I will be closing this issue.  Please feel free to reach out should you run into any additional problems.

**Comment by aikanarov** [comment]
Hi,

I have moncli 0.1.5 installed and have the same problem, I would like to change the status of an item but get this same error.

Version
`Name: moncli
Version: 0.1.5
Summary: Moncli, a pythonic/DDD client for Monday.com
Home-page: https://github.com/trix-solutions/moncli
Author: Andrew Shatz, Trix Solutions
Author-email: andrew.shatz@trix.solutions
License: UNKNOWN
Location: /home/ubuntu/anaconda3/lib/python3.6/site-packages
Requires: requests, nose
Required-by: `

Process:
`
# Create Item
day = dt.datetime.now()
item_name = f'Getting Tweets | {day.strftime("%Y-%m-%d %H:%M:%S")}'
group_id='topics'

item = board.add_item(item_name=item_name, group_id=group_id)
print(f'Id: {item.id} | Name: {item.name}')

# Try to change status

status_value = create_column_value(id='status', title='Status', column_type=ColumnType.status, label='Done')
item = item.change_column_value(column_value=status_value)

And get this error:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-270-35dcbe8fb828> in <module>
----> 1 status_value = create_column_value(id='status', title='Status', column_type=ColumnType.status, label='Done')
      2 item = item.change_column_value(column_value=status_value)

~/anaconda3/lib/python3.6/site-packages/moncli/columnvalue.py in create_column_value(id, column_type, title, **kwargs)
    680 
    681         if kwargs.__contains__('label'):
--> 682             return StatusValue(id, title, label=kwargs['label'], settings=kwargs['settings'])
    683 
    684         if kwargs.__contains__('index'):

KeyError: 'settings'

`
