### ISSUE TITLE
Adding people to an item not working?

### ISSUE THREAD

**Issue by lehnertz85** [trix-solutions/moncli#26]
It appears the add_people() function is not working. Perhaps, I'm not doing right. I followed your documentation and code and I'm pretty sure everything is correct, but people are not being added to my items. Everything else works great.

user_ids is a list of user's ids. 

1. I get the board id.
2. Then get the group id.
3. Then add the item to the appropriate group.
4. Once I have the task(item) object, I call get_column_value().
5. I iterate over the user ids and attempt to add them to the item with add_people().

```
def create_item(client, board_id, group_id, task_name, user_ids):
    print("Creating items")
    task = None
    try:
        the_board = client.get_board(id=board_id)
        the_group = the_board.get_group(id=group_id)
        print("Creating item --- {0} ---".format(task_name))
        print(user_ids)
        task = the_group.add_item(item_name=task_name)
        t = task.get_column_values()
        for value in t:
            if type(value) == PeopleValue:
                for personid in user_ids:
                    print("adding owner ---- {0}".format(personid))
                    value.add_people(id=personid, kind=PeopleKind.person)
                    print("The people are:::: {0}".format(value.persons_and_teams))
    except Exception as e:
        print("ERROR:::::: {0}".format(e))
    return task_id
```

**The `person_and_teams` list does reflect the change**, but nothing shows up in Monday. 

I also tried using the add_item() function on a group object with the `column_values=column_values` parameter (dictionary), but that didn't work either.

Any suggestions?

I really like the idea of automating some of my boards. It can get quite tedious to build them out in the GUI. Adding people is essential in our organization.

**Comment by Ashatz** [comment]
Hello @lehnertz85, yes that does seem like quite the concern.  I will take a look into this.

Also, just so that you are aware, I would like to make another minor release within the next week or two that clean up many of the initial problems like these.  

All the best!

**Comment by lehnertz85** [comment]
Awesome! Thanks!

**Comment by Ashatz** [comment]
Hello @lehnertz85,

I apologize for getting back to you so late.  

As for your issue, the add_people method associated with the **PeopleColumn** object ONLY adds people to the object locally.  To save it to monday.com, you will need to pass the column value into the _update_column_value_ on the Item object.  In the case of your code, it should look like so:
`
value.add_people(id=personid, kind=PeopleKind.person)
task.update_column_value(column_value=value)
`

I will be closing this ticket out.  Please let me know if you have any additional questions or concerns.

**Comment by lehnertz85** [comment]
I'm just getting around to using moncli again. Thanks for the help! I tried `update_column_value` but it didn't work. I discovered the function is actually called `change_column_value` and it works!
