### ISSUE TITLE
Error Installing moncli

### ISSUE THREAD

**Issue by moodybox** [trix-solutions/moncli#31]
using "pip install moncli" I get the following error:

```
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/man/man1/nosetests.1'
Consider using the `--user` option or check the permissions.
```

**Comment by Ashatz** [comment]
@moodybox, from the looks of it, your current user from which you are trying to execute the command does not have proper permissions to write to the python "site-packages" directory.

Are you running Python on Windows or Mac?

**Comment by Ashatz** [comment]
@moodybox, I have not heard a reply back from you, so I will be closing this issue.  Please open up another ticket if you continue to run into this problem.

Thank you!
