### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by marcelocecin** [trix-solutions/moncli#34]
Hi there ! Can you provide an example of query for Files ? Thanks !

**Comment by Ashatz** [comment]
@marcelocecin the file functionality has not yet been put in.  I have a minor release in the works at the moment and will very likely put it in there.  I will label this ticket as a feature request and keep you posted on the progress.

**Comment by Ashatz** [comment]
Hello @marcelocecin, 

This feature is now available in moncli and has been released with v. 0.2.0.  You can update your moncli package using the `pip install --upgrade moncli`.
