### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by marcelocecin** [trix-solutions/moncli#35]
Hi there ! Can you provide an example to verify a Webhook ? Thanks !

**Comment by Ashatz** [comment]
@marcelocecin, much like the files, this functionality has not been implemented yet.  Labeling issue as enhancement

**Comment by Ashatz** [comment]
@marcelocecin,

Adding and removing webhooks has been implemented and have been pushed to PyPI.

Thank you for your patience!
