### ISSUE TITLE
Feature Request: Requests timeout

### ISSUE THREAD

**Issue by alexalligator** [trix-solutions/moncli#36]
### Feature request:
Could you add a timeout to the requests sent to monday?

Ideally I would suggest making this an optional parameter (with sensible default) than can be passed when initialising the client:
```
class MondayClient():
    def __init__(self, user_name: str, api_key_v1: str, api_key_v2: str, timeout:int=10):
```
The client would then send the timeout to all the api functions (in the same way api_key is passed along to every function call).
```
boards_data = client.get_boards(
            self.__creds.api_key_v2, 
            self.timeout,
            'id', 
            'name', 
            **kwargs)
```
Or else, just hardcode a reasonable timeout into all the requests (10 seconds?).

What do you think?

P.S. Thanks for this awesome library :)

**Comment by Ashatz** [comment]
@alexalligator I think a 10 second timeout would be reasonable for all requests.  Thank you bringing the idea forward.  I will get around to this as soon as I am able.

**Comment by Ashatz** [comment]
@alexalligator, this has been merged into master.  Thank you for your contribution!
