### ISSUE TITLE
How I can update the status column of item using label?

### ISSUE THREAD

**Issue by Nishant1507** [trix-solutions/moncli#39]

**Comment by Nishant1507** [comment]
I found it in the code moncli/tests/columnvalue_tests.py.

**Comment by Ashatz** [comment]
Hello @Nishant1507, 

You can use the label property on a status column value object. 
https://github.com/trix-solutions/moncli#statusvalue

So long as you retrieve the column value directly from the board (with column settings applied), the id will always match its corresponding set label.  Then use the column value to update the item.

I am glad that you have found a resolution to your issue.  If you run into another problem, don't hesitate to open an issue.

Thanks!
