### ISSUE TITLE
Unable to install version 0.1.7 for dropdown values

### ISSUE THREAD

**Issue by ccolligan** [trix-solutions/moncli#44]
I would like to install version 0.1.7 so that I can get dropdown values instead of just the value IDs. When trying to install version 0.1.7 I get an error:

```
mbp ~ % pip3 install --user moncli==0.1.7 
ERROR: Could not find a version that satisfies the requirement moncli==0.1.7 (from versions: 0.1, 0.1.1, 0.1.2, 0.1.4, 0.1.5, 0.1.6)
ERROR: No matching distribution found for moncli==0.1.7
```

Is there any other way to get the text values from a dropdown with version 0.1.6? If not, how would I go about getting access to 0.1.7?

**Comment by ccolligan** [comment]
I would also recommend adding the same functionality for dropdown text to the status field type.

**Comment by spotmonk** [comment]
looks like PyPI has 0.1.6 as the latest version and 0.1.7 can't be installed via pip

**Comment by Ashatz** [comment]
The latest version has been updated with all of the pull requests.  Thank you for your patience!
