### ISSUE TITLE
1.0.5 issues: create_column_value

### ISSUE THREAD

**Issue by 1CE9** [trix-solutions/moncli#88]
Hi, I am encountering issues after upgrading today to the latest version 1.0.5, 

`column_value = create_column_value(id='check', column_type=ColumnType.checkbox, checked=True)`
This line gives me this error
`schematics.exceptions.DataError: {"checked": "Rogue field"}`

I don't have this error if I don't specify the value and change it after creation:
`column_value = create_column_value(id='check', column_type=ColumnType.checkbox)`
`column_value.checked = True`

The above occurs within a view object returned by .items(), it does not trigger the error outside of it

**Comment by Ashatz** [comment]
Hello @1CE9, 

This is a documentation issue.  I will make the updates and post them. In the meantime, if you are trying to update column values for an item on a board, I would suggest creating column methods from the board directly as seen below:

`column_value = board.get_column_value('INSERT_COLUMN_ID')`

I will have updates to the documentation ready before end-of-day today.  Please let me know if this works for you.

**Comment by 1CE9** [comment]
@Ashatz Thanks for the swift reply, just a little thing I noticed

```
column_value = board.get_column_value(COLUMN_ID)
column_value.text = text_of_the_cell
items = board.get_items_by_column_values(column_value)
```

I get an empty list if I use `column_value.text = text_of_the_cell`, but not if I use `column_value.value = text_of_the_cell`

**Comment by 1CE9** [comment]
There is too much time consuming little issues with this new version for me, I am going to close this as I am now using the Monday v2 API directly with GraphQL, but thanks for the help and work on this CLI tool and Python Client.

**Comment by Ashatz** [comment]
Hello @1CE9, 

I apologize for the late reply.  You can still use moncli to execute GraphQL queries.  

`
from moncli.api_v2 import requests as r

# Assuming API key stored as string
result: obj = r.execute_query(api_key, query="INSERT_QUERY_HERE")
`
This will allow you to work with data in primitive types and offer more flexibility for you.  Please let me know if this works for you.
