### ISSUE TITLE
Can't retrieve update's files 

### ISSUE THREAD

**Issue by Omersh1** [trix-solutions/moncli#92]
Hi,

I'm trying to get update's file:
```
update = item.get_updates()[0]
f = update.get_files('name', 'url')
```

However, I get a timeout error:
_requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.monday.com', port=443): Read timed out. (read timeout=10)

Let me know if you need more info!

**Comment by Ashatz** [comment]
Hello @Omersh1,

A fix has been merged and is ready for download as v1.0.9.

I have increased the timeout of both file upload and download processes to 5 minutes as opposed to the default 10 seconds.  

Please let me know if you still run into issues with this.
