### ISSUE TITLE
group.py have errors on mutiple values for keyword argument 'groups'

### ISSUE THREAD

**Issue by marcuslow** [trix-solutions/moncli#94]
This error occur in get_items where if the caller supplied a kwargs parameter, the call will have mutiple "groups" defined.

group.py / get_items

        ```
        args = ['groups.items.' + field for field in args]
        if kwargs:
            kwargs = {'groups': {'items': kwargs, 'ids': [self.id]}}
            
        items_data = client.get_boards(
            self.__creds.api_key_v2, 
            *args,
            ids=[int(self.__board_id)],
            limit=1,
            groups={'ids': [self.id]},
            **kwargs)[0]['groups'][0]['items']
        
```

Error : 
got multiple values for keyword argument 'groups'

kwargs = {'groups': {'items': kwargs, 'ids': [self.id]}}
groups={'ids': [self.id]},

Solution is to either get rid of "groups" in the api call or dont use "groups" key in filling in the "items"

**Comment by Ashatz** [comment]
@marcuslow, this bug has been fixed and merged into master and pushed up to the package index.  Please feel free to upgrade your moncli to v1.0.8.
